name: Scala CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: compile
        run: sbt compile
      - name: test compile
        run: "sbt test:compile"
      - name: Run tests
        run: sbt test
